[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = ['cd server && npm ci']

[phases.build]
cmds = ['echo "No build step needed for server"']

[start]
cmd = 'cd server && node server.js'
