[phases.setup]
providers = ["node", "..."]

[phases.setup.nixPkgs]
nodejs = "nodejs_20"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx vite preview --host 0.0.0.0 --port $PORT"
